# Generated by Django 2.0.7 on 2018-12-08 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='comentario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='foro.Comentario'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='foro.Post'),
        ),
    ]
