# Generated by Django 2.0.7 on 2018-12-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_auto_20181208_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comentario',
        ),
    ]
