# Generated by Django 2.0.7 on 2018-12-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0004_auto_20181208_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='emisor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='topico',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
