# Generated by Django 2.0.7 on 2018-12-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0005_auto_20181208_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=1000, verbose_name='Comentario'),
        ),
    ]
