# Generated by Django 2.1.3 on 2018-12-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapa',
            old_name='name',
            new_name='nombre',
        ),
    ]
