# Generated by Django 2.1.3 on 2018-12-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0002_auto_20181202_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapa',
            old_name='user',
            new_name='dueño',
        ),
    ]
